name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish Helm Charts
        uses: J12934/helm-gh-pages-action@master
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
  sixteen:
    runs-on: ubuntu-16.04
    steps:
      - run: helm version
  eighteen:
    runs-on: ubuntu-18.04
    steps:
      - run: helm version
