name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Publish Helm Charts
      uses: J12934/helm-gh-pages-action@bfb6f570f27d684ddabc7efe023717820e28291b
      with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages

